version: '3.8'

services:
  db:
    image: postgres:16
    container_name: odoo16-db
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo16@2023
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  odoo16:
    image: aungminsoe914/odoo16_en_images:latest
    container_name: odoo16-web
    user: root
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "20016:8072"  # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo16@2023
    volumes:
      - ./addons:/mnt/extra-addons                  # ✅ Custom addons
      - ./etc/odoo.conf:/etc/odoo/odoo.conf         # ✅ Config file
      - ./logs/odoo16.log:/etc/odoo/odoo-server.log    # ✅ Log file
    restart: always

  
